[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
verifyskills_contract = "Db5UP4RJdvubepNdsQN6Cgk8sGocmzZiqgZTrVHhDwcR"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
